webservers:
  hosts:
    web1:
      ansible_host: web1
      server_name: "Development Server"
      site_title: "Dev Environment"
      background_color: "#e3f2fd"
    web2:
      ansible_host: web2
      server_name: "Staging Server"
      site_title: "Staging Environment"
      background_color: "#fff3e0"
  vars:
    ansible_user: root
    ansible_password: password
    ansible_connection: ssh